export FZF_DEFAULT_COMMAND="rg --files --hidden --no-ignore-vcs"
export CLICOLOR=1
export EDITOR=nvim
export VISUAL=$EDITOR
export PAGER=less
export LESS='-F -i -R -S -w -X -z-4'
export HOMEBREW_NO_AUTO_UPDATE=1
export PATH="/Users/john/bin:$PATH"
export GOOGLE_APPLICATION_CREDENTIALS=/Users/john/.config/gcloud/application_default_credentials.json
export ANDROID_HOME=/Users/john/Library/Android/sdk
export PATH="$ANDROID_HOME/platform-tools:$PATH"
